name: Update Portal

on:
  push:
    branches: 
      - master 
 

jobs:
  update-portal:
    runs-on: ubuntu-latest
    
    env: 
      API_ENTITY_ID: '61530385482a23ea938753f4'
      AUTHORIZATION: 'Basic b2JhaWQua2hhdHRha0BhcGltYXRpYy5pbzpCaWdkYWRkeS4xMjM='
    steps:
    
    - name : checkout-repo
      uses: actions/checkout@v1
      id: checkout-repo 

    - name: Install zip action
      uses: montudor/action-zip@v0.1.1    
      
    - name: install zip 
      run: sudo apt-get install zip unzip
      
    - name: zip files
      run: zip -r portal-input.zip *
      working-directory: Specs

    - name: list
      run: zip -sf portal-input.zip
      working-directory: Specs

    - name: inplace-import
      run: curl -X PUT --url 'https://www.apimatic.io/api/api-entities/${{ env.API_ENTITY_ID }}' -H 'Content-Type:multipart/form-data' -H 'Accept:application/json' -H 'Authorization:${{ env.AUTHORIZATION }}' -F 'file=@Specs/portal-input.zip'

      
    - name: publish-portal
      run: curl -X PUT 'https://www.apimatic.io/api/api-entities/${{ env.API_ENTITY_ID }}/portal/publish' -H 'Content-Length:0' -H 'Content-Type:application/json' -H 'Accept:application/json' -H 'Accept-Encoding:gzip,deflate,br' -H 'Authorization:${{ env.AUTHORIZATION }}'
    # run: curl -X PUT --url "https://www.apimatic.io/api/api-entities/portals/publish" -H "accept:application/json" -H "Authorization:${{ secrets.CREDENTIALS }}" -H "content-type:application/json" --data-raw "{\"apiEntityIds\":[\"${{ env.API_ENTITY_ID }}\"]}"
   
