name: Update Portal

on:
  push:
    branches: 
      - master 
 

jobs:
  update-portal:
    runs-on: ubuntu-latest
    
    env: 
      API_ENTITY_ID: 6128cfc0e0534a34da6cc472  
    steps:
    
    - name : checkout-repo
      uses: actions/checkout@v1
      id: checkout-repo 

    - name: Install zip action
      uses: montudor/action-zip@v0.1.1    
      
    - name: install zip 
      run: sudo apt-get install zip unzip
      
    - name: zip files
      run: zip -r portal-input.zip *
      working-directory: Specs
    
    - name: Upload 
      uses: Difegue/action-megacmd@master
      with:
        args: put Specs/portal-input.zip exportedfiles
      env:
        USERNAME: odion1@yopmail.com
        PASSWORD: odionighalo


    - name: list
      run: zip -sf portal-input.zip
      working-directory: Specs

    - name: inplace-import
      run: curl -X PUT --url 'https://www.apimatic.io/api/api-entities/${{ env.API_ENTITY_ID }}' -H 'content-type:multipart/form-data' -H 'Authorization:${{ secrets.CREDENTIALS }}' -F 'file=@Specs/portal-input.zip'

      
    - name: publish-portal
      run: curl -X PUT --url "https://www.apimatic.io/api/api-entities/portals/publish" -H "accept:application/json" -H "Authorization:${{ secrets.CREDENTIALS }}" -H "content-type:application/json" --data-raw "{\"apiEntityIds\":[\"${{ env.API_ENTITY_ID }}\"]}"
